### ISSUE TITLE
Errors with some extensions

### ISSUE THREAD

**Issue by tsound97** [TheLastBen/fast-stable-diffusion#330]
After update the repo, there is something wrong with the extensions "deforum” and “sd-dynamic-prompts”

Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 155, in load_scripts
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 12, in <module>
    from prompts.wildcardmanager import WildcardManager
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/wildcardmanager.py", line 4, in <module>
    from .wildcardfile import WildcardFile
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/wildcardfile.py", line 3, in <module>
    class WildcardFile:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/wildcardfile.py", line 8, in WildcardFile
    def get_wildcards(self) -> set[str]:
TypeError: 'type' object is not subscriptable

Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [a0f51ae8] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/LucynaKushinada.ckpt
Loading VAE weights from: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/LucynaKushinada.vae.pt
Applying cross attention optimization (Doggettx).
Model loaded.
no display name and no $DISPLAY environment variable
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Error executing callback ui_tabs_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 67, in ui_tabs_callback
    res += c.callback() or []
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 246, in on_ui_tabs
    components = deforum_args.setup_deforum_setting_dictionary(None, True, True)
AttributeError: module 'scripts.deforum.args' has no attribute 'setup_deforum_setting_dictionary'

**Comment by tsound97** [comment]
It seems this script only works on python 3.11

**Comment by TheLastBen** [comment]
> It seems this script only works on python 3.11

does the script dev has a repo ?

**Comment by tsound97** [comment]
Here is their github link: 
https://github.com/adieyal/sd-dynamic-prompts
https://github.com/deforum-art/deforum-for-automatic1111-webui
