### ISSUE TITLE
Xformers problem?

### ISSUE THREAD

**Issue by dankchocolate** [TheLastBen/fast-stable-diffusion#2280]
Keep getting this, tried delete and reinstall notebook. No luck.

=================================================================================
You are running xformers 0.0.18.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
2023-06-27 06:51:50,625 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-06-27 06:51:51,185 - ControlNet - INFO - ControlNet v1.1.227
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: preload_extensions_git_metadata for 8 extensions took 0.62s
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 477, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 390, in webui
    app, local_url, share_url = shared.demo.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'app_kwargs'
4c86efd062ea772972dd068c3870773f1fd9a37ba9a288ee79ec848448ce7785
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json100% 961k/961k [00:00<00:00, 2.82MB/s]
Downloading (…)olve/main/merges.txt100% 525k/525k [00:00<00:00, 2.07MB/s]
Downloading (…)cial_tokens_map.json100% 389/389 [00:00<00:00, 1.66MB/s]
Downloading (…)okenizer_config.json100% 905/905 [00:00<00:00, 4.62MB/s]
Downloading (…)lve/main/config.json100% 4.52k/4.52k [00:00<00:00, 27.8MB/s]
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0): 
Model loaded in 72.1s (calculate hash: 17.3s, load weights from disk: 42.0s, create model: 3.8s, apply weights to model: 3.6s, apply half(): 3.5s, move model to device: 1.7s, calculate empty prompt: 0.2s).

**Comment by Hunterclaw** [comment]
Just got something similar. So I guess I'll wait while it gets resolved,

**Comment by dankchocolate** [comment]
At least I know it isn't me being a dumbass this time.

**Comment by TheLastBen** [comment]
working on it

**Comment by QinCaii** [comment]
still
