### ISSUE TITLE
AttributeError: 'State' object has no attribute 'need_restart'

### ISSUE THREAD

**Issue by EntityinArray** [TheLastBen/fast-stable-diffusion#337]
AttributeError: 'State' object has no attribute 'need_restart'

![image](https://user-images.githubusercontent.com/18554021/199475681-f5712acb-d4fe-424e-9283-f57d27bf575e.png)
Tried checking "Update repo" checkbox, didn't help, shows the same error

**Comment by EntityinArray** [comment]
Problem fixed after I removed the sd folder from my google drive and reran the notebook

**Comment by TheLastBen** [comment]
you don't need to remove the sd folder, you can just check the box "update_repo" in the second cell

**Comment by EntityinArray** [comment]
> you don't need to remove the sd folder, you can just check the box "update_repo" in the second cell

I tried doing this, but it didn't work on its own. Only removing the sd folder helped

**Comment by TheLastBen** [comment]
Use the latest colab from the official link, old versions of the notebook might cause errors.
