### ISSUE TITLE
Blocks.launch() got an unexpected keyword argument 'app_kwargs'

### ISSUE THREAD

**Issue by profcat2** [TheLastBen/fast-stable-diffusion#2283]
I think this is similar problem to the xformers issue posted by another user. I'm getting this error:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 477, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 390, in webui
    app, local_url, share_url = shared.demo.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'app_kwargs'

It was working okay before the update the other day. Please help!
Thanks!

**Comment by Toshik-One** [comment]
I have the same problem too. The link to the web interface does not even appear in the console . 

=================================================================================
You are running xformers 0.0.18.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
Loading weights [8e96063058] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/2339MixFishMixTheOther_v10.safetensors
preload_extensions_git_metadata for 7 extensions took 0.00s
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 477, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 390, in webui
    app, local_url, share_url = shared.demo.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'app_kwargs'
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0): 
Model loaded in 40.7s (load weights from disk: 20.4s, create model: 10.9s, apply weights to model: 3.1s, apply half(): 3.9s, move model to device: 2.2s, calculate empty prompt: 0.2s).

After that it stops .

**Comment by Tonkatsu-01** [comment]
got the same issue. hope bro Ben can fix this.

**Comment by Toshik-One** [comment]
The error appeared most likely that today Automatic1111 Web UI update, version 1.4.0 was released

**Comment by ryanjin** [comment]
it works good with latest Notebook

**Comment by xhhjin** [comment]
Solve it by upgrade gradio>=3.32.0, please have a try by: pip install -U gradio

More info in [https://www.gradio.app/changelog#version-3-32-0](https://www.gradio.app/changelog#version-3-32-0)

Interface.launch() and Blocks.launch() now accept an app_kwargs argument to allow customizing the configuration of the underlying FastAPI app, by [@akx](https://github.com/akx) in [PR 4282](https://github.com/gradio-app/gradio/pull/4282)
