### ISSUE TITLE
 cannot import name 'sd_unet' from 'modules' (unknown location)

### ISSUE THREAD

**Issue by EzHeViQa** [TheLastBen/fast-stable-diffusion#2290]
Today I started getting this error when trying to start stable diffusion in free colab

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 49, in <module>
    from modules import shared, sd_samplers, upscaler, extensions, localization, ui_tempdir, ui_extra_networks, config_states
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 9, in <module>
    from modules import sd_samplers_common, prompt_parser, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_common.py", line 5, in <module>
    from modules import devices, processing, images, sd_vae_approx, sd_samplers, sd_vae_taesd
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 17, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config, sd_unet
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

**Comment by profcat2** [comment]
The free colab version isn't supported anymore, try upgrading to Colab Pro

**Comment by johntable0405** [comment]
Also getting on paid colab

**Comment by TheLastBen** [comment]
try running it without the first cell

**Comment by EzHeViQa** [comment]
> try running it without the first cell

You are running xformers 0.0.18.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
Calculating sha256 for /content/model.safetensors: preload_extensions_git_metadata for 7 extensions took 0.00s
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 477, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 390, in webui
    app, local_url, share_url = shared.demo.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'app_kwargs'
853e7e85c46be9ad4815666cd335545df32dab5e0d22afe5ccc6ad9bda834b52
Loading weights [853e7e85c4] from /content/model.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json100% 961k/961k [00:00<00:00, 5.91MB/s]
Downloading (…)olve/main/merges.txt100% 525k/525k [00:00<00:00, 61.2MB/s]
Downloading (…)cial_tokens_map.json100% 389/389 [00:00<00:00, 2.04MB/s]
Downloading (…)okenizer_config.json100% 905/905 [00:00<00:00, 5.80MB/s]
Downloading (…)lve/main/config.json100% 4.52k/4.52k [00:00<00:00, 21.7MB/s]
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0): 
Model loaded in 22.1s (calculate hash: 8.7s, load weights from disk: 4.3s, create model: 3.0s, apply weights to model: 4.0s, apply half(): 1.0s, move model to device: 0.8s, calculate empty prompt: 0.2s).

and after this it stopped

**Comment by EzHeViQa** [comment]
> try running it without the first cell

Looks like i didn't have sd_unet.py in modules folder on my Google drive. I downloaded it and now everything works fine
